import { ZODL_URL, EXCHANGES, ZINGO_URL, AMOUNT } from "./config.js";

// Step cards. Text supports **bold** and `code`. Keep it short: one line of why, then the taps.
// kind: "confirm" (you say it's done), "verify" (we watch your public address),
// "letter" (write, copy, send), "faucet" (free test ZEC, testnet only).
export const ROUNDS = {
  test: {
    path: "/testnet",
    tag: "Practice · Testnet",
    title: "Your first sealed letter",
    sub: "Free practice coins. Every step is watched for you.",
    other: { title: "Ready for real?", text: "Same six steps with a dollar or two of ZEC.", label: "Go to Mainnet", href: "/mainnet" },
    steps: [
      {
        title: "Set up Zingo",
        sub: "About 3 minutes",
        lead: "Zingo can switch to testnet, where coins are free.",
        list: [
          "Install **Zingo**.",
          "**☰** → **Options** → **⚙** → **Server**.",
          "**Network**: **Testnet**. Keep **Automatic**. Tap **Save**.",
          "Tap **Create New Wallet**.",
        ],
        links: [{ label: "Get Zingo", href: ZINGO_URL }],
        tips: [
          { title: "You're on testnet when", text: "the balance says **TAZ** and your address starts with **utest1**." },
          { title: "Already use Zingo?", text: "Save your seed first: **☰** → **Options** → **Wallet Seed**." },
        ],
        shots: [
          { src: "/guide/zingo-settings.jpg", cap: "Settings → Server" },
          { src: "/guide/zingo-server.jpg", cap: "Network: Testnet" },
          { src: "/guide/zingo-welcome.jpg", cap: "Create New Wallet" },
          { src: "/guide/zingo-receive.jpg", cap: "TAZ 0 · you're in" },
        ],
        kind: "confirm",
        confirm: "My wallet says TAZ",
      },
      {
        title: "Get test ZEC",
        sub: "One tap, free",
        lead: "We send 1 free test ZEC to your private balance.",
        list: [
          "In Zingo, tap **Receive** and copy your address (**utest1…**).",
          "Paste it below and tap **Send me test ZEC**.",
        ],
        kind: "faucet",
        confirm: "It's in my Zingo",
      },
      {
        title: "Move some to your public address",
        sub: "Private to public",
        lead: "Exchanges use public addresses. Practice sending to yours.",
        list: [
          "In **Receive**, switch **Shielded Address** to **Transparent**. Copy it (**tm…**).",
          "Paste it below.",
          "In Zingo, **Send** `0.002` to that same address.",
        ],
        note: "Spendable shows 0? Wait for Zingo to finish syncing.",
        kind: "verify",
        check: "arrive",
        ask: true,
        watching: "Waiting for your coins…",
        watchingSub: "This turns green by itself.",
      },
      {
        title: "Shield it back",
        sub: "Public to private",
        lead: "Tap **Shield** in Zingo and confirm.",
        note: "No Shield button yet? New coins need a few minutes.",
        kind: "verify",
        check: "shield",
        watching: "Waiting for your shield…",
        watchingSub: "This turns green by itself.",
      },
      {
        title: "Seal a practice letter",
        sub: "To future you",
        lead: "Send a tiny amount to yourself, with your letter inside.",
        list: [
          "Write it below. Tap **Copy letter**.",
          `In Zingo: **Send** → your **utest1** address → \`${AMOUNT}\` → paste in **Memo**.`,
        ],
        kind: "letter",
        confirm: "I sent it",
      },
      {
        title: "Read it back",
        sub: "Only you can",
        lead: "Open the new transaction in Zingo. Your letter is there.",
        tips: [
          { title: "Everyone else sees", text: "No sender, no amount, no letter." },
          { title: "You see", text: "All of it." },
        ],
        kind: "confirm",
        confirm: "I can read my letter",
      },
    ],
  },
  main: {
    path: "/mainnet",
    tag: "Real · Mainnet",
    title: "Seal a letter to future you",
    sub: "A dollar or two of ZEC. It comes back to you.",
    other: { title: "New to this?", text: "Practice first. Free, same steps.", label: "Go to Testnet", href: "/testnet" },
    steps: [
      {
        title: "Set up Zodl",
        sub: "About 5 minutes",
        lead: "Zodl keeps your ZEC private by default.",
        list: [
          "Install **Zodl** and tap **Create New Wallet**.",
          "Back up your recovery phrase on paper: **Settings** → **Advanced**.",
        ],
        links: [{ label: "Get Zodl", href: ZODL_URL }],
        video: "/videos/1.mp4",
        kind: "confirm",
        confirm: "My wallet is ready",
      },
      {
        title: "Get a little ZEC",
        sub: "A dollar or two",
        lead: "Buy on an exchange and withdraw to your public address.",
        list: [
          "In Zodl, tap **Receive** and copy your **t1…** address.",
          "Paste it below, then withdraw to it.",
        ],
        links: EXCHANGES,
        video: "/videos/2.mp4",
        kind: "verify",
        check: "arrive",
        ask: true,
        skip: { label: "I used Swap in Zodl instead", skips: 2 },
        watching: "Waiting for your ZEC…",
        watchingSub: "This turns green by itself.",
      },
      {
        title: "Shield it",
        sub: "Public to private",
        lead: "Tap **Shield** on your Unshielded Balance and confirm.",
        note: "No Shield button yet? New coins need a few minutes.",
        video: "/videos/3.mp4",
        kind: "verify",
        check: "shield",
        watching: "Waiting for your shield…",
        watchingSub: "This turns green by itself.",
      },
      {
        title: "Seal a letter",
        sub: "To future you",
        lead: "Send a tiny amount to yourself, with your letter inside.",
        list: [
          "Write it below. Tap **Copy letter**.",
          `In Zodl: **Send** → your **u1** address → \`${AMOUNT}\` → paste in **Message**.`,
        ],
        video: "/videos/4.mp4",
        kind: "letter",
        confirm: "I sent it",
      },
      {
        title: "Read it back",
        sub: "Only you can",
        lead: "Tap the new transaction in **Activity**. Your letter is there.",
        tips: [
          { title: "Everyone else sees", text: "No sender, no amount, no letter." },
          { title: "You see", text: "All of it." },
        ],
        video: "/videos/5.mp4",
        kind: "confirm",
        confirm: "I can read my letter",
      },
      {
        title: "Unshield",
        sub: "Private to public",
        lead: "Exchanges use public addresses. Practice sending to yours.",
        list: ["In Zodl, **Send** `0.0005` to your own **t1** address."],
        note: "Not enough yet? Your letter's change needs a few minutes.",
        video: "/videos/6.mp4",
        kind: "verify",
        check: "back",
        watching: "Waiting for your ZEC…",
        watchingSub: "This turns green by itself.",
      },
    ],
  },
};

// Lost in the post? Answers about how Zender works. test/main: shown on that round only.
export const FAQ = [
  { q: "How does a step turn green by itself?", a: "Zender looks up the public address you pasted on the Zcash chain about every 20 seconds. A new block lands about every 75 seconds, so give it a minute or tap Check now." },
  { q: "Why do I tick some steps myself?", a: "Private sends can't be seen by anyone, Zender included. That's the point, so you confirm those steps." },
  { q: "Send me test ZEC didn't work", a: "Paste your private address, the one that starts with utest1. If the faucet is busy, use the faucet site link under the button.", test: true },
  { q: "Is test ZEC worth anything?", a: "No. It shows as TAZ in Zingo and has no value. It's only for practice.", test: true },
  { q: "Can I skip the exchange?", a: "Yes. If you bought ZEC with Swap in Zodl, tap I used Swap in Zodl instead in step 2.", main: true },
  { q: "There's no Shield button in Zodl", a: "New coins need a few minutes to confirm. Shield appears on your Unshielded Balance once they do.", main: true },
  { q: "Where does my letter go?", a: "Into the memo of a send to yourself. It's encrypted on the chain and only your wallet can open it. Zender never sends or saves it." },
  { q: "What can Zender see?", a: "Only the public address you paste. Never your letter, your recovery phrase or your keys." },
];
